### ISSUE TITLE
[q] how to add on click to RecycleView (to detect when images are clicked)

### ISSUE THREAD

**Issue by vladp** [athkalia/Just-Another-Android-App#47]
would be great if the sample shows how to add an onClick to recycleview.
Given the number of libries/tools used (mosby,butterknife, rxjava) it was not clear to me the proper idiomatic way of implementing this.

thx in advance for any pointers.

**Comment by athkalia** [comment]
Hello,

Have a look at this cool presentation, touches click listeners about half way through. 
https://realm.io/news/360andev-yigit-boyar-pro-recyclerview-android-ui-java

This has an updated approach to use an RxJava PublishSubject 
http://stackoverflow.com/questions/24885223/why-doesnt-recyclerview-have-onitemclicklistener-and-how-recyclerview-is-dif

I am planning to add a details activity under https://github.com/athkalia/Just-Another-Android-App/issues/48 eventually, but it's going to take a while as I have other priorities at the moment.

Cheers

**Comment by vladp** [comment]
thank you for the pointer
