### ISSUE TITLE
Create a details Activity

### ISSUE THREAD

**Issue by miguelslemos** [athkalia/Just-Another-Android-App#48]
Hello, there is any possibility to add a details activity? I would like to see how works with SubComponent and etc..

**Comment by athkalia** [comment]
Hello,

Thank you for your message. I do have plans, to add a details screen, but not immediate plans. So expect this in the 3-6 months range. Always accepting PRs as well.

**Comment by miguelslemos** [comment]
I'm working on creating a details screen, I'll open PR in soon

**Comment by athkalia** [comment]
sure thing pal

**Comment by Rainer-Lang** [comment]
@miguelslemos Any news?

**Comment by athkalia** [comment]
Closing this - project no longer maintained. I don't recommend making any additions to it, as most of the programming paradigms and technologies used here are a bit out of date these days 😅
