### ISSUE TITLE
Was very tricky to integrate React-native into the app

### ISSUE THREAD

**Issue by vladp** [athkalia/Just-Another-Android-App#54]
This is not a bug.

But it turned out to be very very tricky to integrate react native into the Just-another-android app.
The problem turned out to be conflict in versions of okhttp

See this discussion
http://stackoverflow.com/questions/43020878/react-native-activity-crashes-probably-related-to-packaging-okhttp3

so just sharing, if others run into it.
 Or may be, it would make sense to add some comments in to the gradle wrt this potential conflict (if it persists in the next couple of iterations of react native).

**Comment by athkalia** [comment]
Thanks for the comment!
I would prefer not to add a comment in the code about react at the moment, as it would only confuse people. Are you happy to close this?

**Comment by vladp** [comment]
yes. sure. closing
