### ISSUE TITLE
Suggestion: Use Dagger 2.11 with AndroidInjector

### ISSUE THREAD

**Issue by Rainer-Lang** [athkalia/Just-Another-Android-App#86]

**Comment by athkalia** [comment]
it's on the schedule, ETA less than a month

**Comment by Rainer-Lang** [comment]
Thanks.

**Comment by athkalia** [comment]
less than a month became 2 days :P
This is the initial PR
https://github.com/athkalia/Just-Another-Android-App/pull/88
I'll probably merge tomorrow

**Comment by athkalia** [comment]
merged

**Comment by Rainer-Lang** [comment]
Impressive ☺️
